main: me.DirkWind.EnderPlayers.Main
name: EnderPlayers
version: 0.1.1
author: DirkWind
api-version: 1.16

commands:
  enderhands:
      description: Sets a player's enderhands value. A value of true means that all blocks considered solid by the spigot
        api will be dropped as their exact block (e.g. grass block will drop grass block), somewhat like an enderman.
      usage: /enderhands <target> {true|false|toggle}
